"""agregar consentimiento a usuario

Revision ID: 444873b25785
Revises: ecb65888ce6f
Create Date: 2026-09-10 15:17:27.934044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444873b25785'
down_revision: Union[str, Sequence[str], None] = 'ecb65888ce6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('consentimiento_datos', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('usuarios', sa.Column('consentimiento_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'consentimiento_en')
    op.drop_column('usuarios', 'consentimiento_datos')
    # ### end Alembic commands ###
