"""feat(db): agregar mediciones con uq_usuario_fecha

Revision ID: ce4773f63c25
Revises: 9579bae4a653
Create Date: 2026-10-05 17:57:26.779122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4773f63c25'
down_revision: Union[str, Sequence[str], None] = '9579bae4a653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_usuario_fecha_medicion', 'mediciones', ['usuario_id', 'fecha'])
    op.create_unique_constraint('uq_sesion_ejercicio_serie', 'series_sesion', ['sesion_id', 'ejercicio_id', 'numero_serie'])
    op.alter_column('sesiones', 'duracion_segundos',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sesiones', 'duracion_segundos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_sesion_ejercicio_serie', 'series_sesion', type_='unique')
    op.drop_constraint('uq_usuario_fecha_medicion', 'mediciones', type_='unique')
    # ### end Alembic commands ###
