"""Creacion inicial de tablas

Revision ID: ecb65888ce6f
Revises: 
Create Date: 2026-09-10 02:30:27.905473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecb65888ce6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_experiencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ejercicios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_es', sa.String(length=100), nullable=False),
    sa.Column('nombre_en', sa.String(length=100), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=50), nullable=False),
    sa.Column('equipo', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('gif_url', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('altura_cm', sa.Integer(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('codigo_gimnasio', sa.String(length=50), nullable=True),
    sa.Column('tiene_experiencia_previa', sa.Boolean(), nullable=True),
    sa.Column('preferencias_notificacion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('dispositivos_notificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_push', sa.String(length=255), nullable=False),
    sa.Column('plataforma', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_push')
    )
    op.create_index(op.f('ix_dispositivos_notificacion_usuario_id'), 'dispositivos_notificacion', ['usuario_id'], unique=False)
    op.create_table('logros_usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo_logro', sa.String(length=50), nullable=False),
    sa.Column('obtenido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'tipo_logro', name='uq_usuario_tipo_logro')
    )
    op.create_index(op.f('ix_logros_usuario_usuario_id'), 'logros_usuario', ['usuario_id'], unique=False)
    op.create_table('mediciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('porcentaje_grasa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('masa_muscular_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('circunf_cintura_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('circunf_cadera_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('circunf_brazo_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('circunf_pierna_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('circunf_pecho_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediciones_usuario_id'), 'mediciones', ['usuario_id'], unique=False)
    op.create_table('rachas',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('racha_actual', sa.Integer(), nullable=False),
    sa.Column('racha_maxima', sa.Integer(), nullable=False),
    sa.Column('ultima_actividad', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('respuestas_onboarding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tiempo_practicando', sa.String(length=50), nullable=False),
    sa.Column('objetivo', sa.String(length=50), nullable=False),
    sa.Column('dias_entrenamiento_semana', sa.Integer(), nullable=False),
    sa.Column('limitaciones_fisicas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respuestas_onboarding_usuario_id'), 'respuestas_onboarding', ['usuario_id'], unique=True)
    op.create_table('rutinas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('favorita', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutinas_usuario_id'), 'rutinas', ['usuario_id'], unique=False)
    op.create_table('tokens_recuperacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_tokens_recuperacion_usuario_id'), 'tokens_recuperacion', ['usuario_id'], unique=False)
    op.create_table('respuesta_experiencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('respuesta_onboarding_id', sa.UUID(), nullable=False),
    sa.Column('experiencia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['experiencia_id'], ['catalogo_experiencias.id'], ),
    sa.ForeignKeyConstraint(['respuesta_onboarding_id'], ['respuestas_onboarding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respuesta_experiencias_experiencia_id'), 'respuesta_experiencias', ['experiencia_id'], unique=False)
    op.create_index(op.f('ix_respuesta_experiencias_respuesta_onboarding_id'), 'respuesta_experiencias', ['respuesta_onboarding_id'], unique=False)
    op.create_table('rutina_ejercicios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rutina_id', sa.UUID(), nullable=False),
    sa.Column('ejercicio_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('series_objetivo', sa.Integer(), nullable=False),
    sa.Column('repeticiones_objetivo', sa.Integer(), nullable=False),
    sa.Column('descanso_segundos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutina_ejercicios_ejercicio_id'), 'rutina_ejercicios', ['ejercicio_id'], unique=False)
    op.create_index(op.f('ix_rutina_ejercicios_rutina_id'), 'rutina_ejercicios', ['rutina_id'], unique=False)
    op.create_table('sesiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rutina_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_sesiones_rutina_id'), 'sesiones', ['rutina_id'], unique=False)
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones', ['usuario_id'], unique=False)
    op.create_table('series_sesion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesion_id', sa.UUID(), nullable=False),
    sa.Column('ejercicio_id', sa.UUID(), nullable=False),
    sa.Column('numero_serie', sa.Integer(), nullable=False),
    sa.Column('repeticiones_realizadas', sa.Integer(), nullable=False),
    sa.Column('peso_usado_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_sesion_ejercicio_id'), 'series_sesion', ['ejercicio_id'], unique=False)
    op.create_index(op.f('ix_series_sesion_sesion_id'), 'series_sesion', ['sesion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_sesion_sesion_id'), table_name='series_sesion')
    op.drop_index(op.f('ix_series_sesion_ejercicio_id'), table_name='series_sesion')
    op.drop_table('series_sesion')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_rutina_id'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_rutina_ejercicios_rutina_id'), table_name='rutina_ejercicios')
    op.drop_index(op.f('ix_rutina_ejercicios_ejercicio_id'), table_name='rutina_ejercicios')
    op.drop_table('rutina_ejercicios')
    op.drop_index(op.f('ix_respuesta_experiencias_respuesta_onboarding_id'), table_name='respuesta_experiencias')
    op.drop_index(op.f('ix_respuesta_experiencias_experiencia_id'), table_name='respuesta_experiencias')
    op.drop_table('respuesta_experiencias')
    op.drop_index(op.f('ix_tokens_recuperacion_usuario_id'), table_name='tokens_recuperacion')
    op.drop_table('tokens_recuperacion')
    op.drop_index(op.f('ix_rutinas_usuario_id'), table_name='rutinas')
    op.drop_table('rutinas')
    op.drop_index(op.f('ix_respuestas_onboarding_usuario_id'), table_name='respuestas_onboarding')
    op.drop_table('respuestas_onboarding')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('rachas')
    op.drop_index(op.f('ix_mediciones_usuario_id'), table_name='mediciones')
    op.drop_table('mediciones')
    op.drop_index(op.f('ix_logros_usuario_usuario_id'), table_name='logros_usuario')
    op.drop_table('logros_usuario')
    op.drop_index(op.f('ix_dispositivos_notificacion_usuario_id'), table_name='dispositivos_notificacion')
    op.drop_table('dispositivos_notificacion')
    op.drop_table('usuarios')
    op.drop_table('ejercicios')
    op.drop_table('catalogo_experiencias')
    # ### end Alembic commands ###
